"""empty message

Revision ID: 0d067ddd2200
Revises: d79aaf6fd803
Create Date: 2018-11-03 17:13:20.633685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d067ddd2200'
down_revision = 'd79aaf6fd803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('token', sa.String(length=34), nullable=True))
    op.create_unique_constraint(None, 'project', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'token')
    # ### end Alembic commands ###
