"""empty message

Revision ID: aba9b0f60438
Revises: f2651dc039b5
Create Date: 2018-11-03 17:11:19.444430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba9b0f60438'
down_revision = 'f2651dc039b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_key', 'user', type_='unique')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_role_key', 'user', ['role'])
    # ### end Alembic commands ###
