"""empty message

Revision ID: ac55dcbdaf3c
Revises: aba9b0f60438
Create Date: 2018-11-03 17:12:06.537290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac55dcbdaf3c'
down_revision = 'aba9b0f60438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
